[dependencies]
  # uuid4cj ={git = "https://gitcode.com/Cangjie-TPC/uuid4cj.git", branch = "cjc_0.53.13"}
  uuid4cj = { path = "./uuid4cj"}

  # charset4cj ={git = "https://gitcode.com/Cangjie-TPC/charset4cj.git", branch = "cjc_0.53.13"}
  charset4cj = { path = "./charset4cj"}

  # csv4cj ={git = "https://gitcode.com/Cangjie-TPC/csv4cj.git", branch = "cjc_0.53.13"}
  csv4cj = { path = "./csv4cj"}

  # crypto4cj ={git = "https://gitcode.com/Cangjie-TPC/crypto4cj.git", tag = "v_0.53.13"}
  crypto4cj = { path = "./crypto4cj"}

  # CJson = {git = "https://gitcode.com/Cangjie-TPC/CJson.git", branch = "master"}

[ffi]
  [ffi.c]
    apirequest = {path = "./lib"}
    duckdb = {path = "./lib"}
    execute_python = {path = "./lib"}
    googlesearch = {path = "./lib"}
    hnswlibcj = {path = "./lib"}
    onnxruntime_cj_api = {path = "./lib"}
    onnxutils = {path = "./lib"}
    serpapisearch = {path = "./lib"}


[package]
  cjc-version = "0.53.13"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "canggraph"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}


